### ISSUE TITLE
potential bugs to fix

### ISSUE THREAD

**Issue by yuxianglin** [erdc-cm/proteus#520] opened 2017-05-05 02:31 UTC
Hi:

The Gauge.py in https://github.com/erdc-cm/proteus/blob/master/proteus/Gauges.py#L266, the first arguments seems erroneous which should be like  (nearest_node_distance, comm.rank).

In Domain.py https://github.com/erdc-cm/proteus/blob/master/proteus/Domain.py#L1049, the h seems need to write in the form of h[0], h[1], h[2]

Yuxiang

**Comment by alistairbntl** [comment] 2017-05-05 06:37
@yuxianglin - Thanks for your comments!  Would you mind answering a few questions so I can get a better sense of these issues?

First, did you encounter these issues while running a program?  If so would you be able to provide some context?  It may make is easier to known how to proceed.

Also, I'm not sure I understand your first comment.  Would you mind clarifying further?  Am I correct to assume you are saying that the `nearest_node_distance` argument should not be part of the `comm.allreduce`?

As for the `writePoly` function, this is used fairly extensively in the library and test suite, so I would assume this is working correctly unless you have come across an case in which it is failing.  If so would you mind sharing? 

Thanks again!

**Comment by adimako** [comment] 2017-05-05 08:35
@yuxianglin @alistairbntl, just to let you know that @Giovanni-Cozzuto-1989 @tridelat and me use the Gauge module frequently and we have not encountered any problems so far, but I 'd like to hear any comments @yuxianglin that could help improve performance.

**Comment by yuxianglin** [comment] 2017-05-05 19:09
Sorry for the confusion.

For the first potential bug, if the gauge point is falling out of the domain, we may encounter such problem showing float is not iterable. I think it needs to modify to 
_global_min_distance, owning_proc = comm.allreduce((nearest_node_distance,comm.rank), op=MPI.MINLOC)_

**Comment by alistairbntl** [comment] 2017-05-08 22:39
@tridelat @adimako - I'm not so familiar with the `comm.allreduce` function, but this suggested change seems to make sense to me.  Can you comment on this recommended change?

As for the second problem, I agree that something looks strange.  Do you have a specific problem you were working on that caused a problem?

**Comment by tridelat** [comment] 2017-05-09 10:31
@yuxianglin , `MINLOC` and `MAXLOC` are supposed to return a tuple of the minimum (or maximum) value and the location (processor rank), so `comm.allreduce` function should not need a tuple `(haveElement, comm.rank)` as first argument in https://github.com/erdc-cm/proteus/blob/master/proteus/Gauges.py#L259 in theory.
But you mentioned that it is https://github.com/erdc-cm/proteus/blob/master/proteus/Gauges.py#L266 so I am not sure what the problem is. 
Maybe the tuple was added because `MAXLOC` and `MINLOC` did not return the rank as intended? It is worth trying to add the tuple `(nearest_node_distance, comm.rank)` as first argument in https://github.com/erdc-cm/proteus/blob/master/proteus/Gauges.py#L266 and see if that solves the problem.

**Comment by yuxianglin** [comment] 2017-05-09 17:46
Yes, I added the tuple as input and it actually resolved the problem.@tridelat

**Comment by alistairbntl** [comment] 2017-05-09 18:26
@yuxianglin : Can you submit a pull request with the correction and some type of test?  I'd be happy to walk you through this is you need a hand.

**Comment by tridelat** [comment] 2017-07-07 15:14
Fixes merged with https://github.com/erdc-cm/proteus/pull/526

**Closed by tridelat** 2017-07-07 15:14 UTC
